version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "5:00"
      timezone: "Europe/Sofia"
    labels:
      - "npm"
      - "dependencies"
    assignees:
      - Sagar-Kap
    commit-message: "chore: "
    ignore:
      - dependency-name: next
        update-types:
          - version-update:semver-major
      - dependency-name: react
        update-types:
          - version-update:semver-major
      - dependency-name: react-dom
        update-types:
          - version-update:semver-major
