version: "3"

silent: true

tasks:
  default:
    desc: List all the available commands
    summary: |
      List all the available commands.

      This command will print a nice and helpful list of all available commands
      and their purposes to STDOUT.
    cmd: task --list

  setup:
    desc: Setup the local development environment
    summary: |
      Setup the dev environment.

      This command will automatically setup the development environment for you.
      It will setup the pre-commit hooks, build the appropriate Docker commands
      and more such commands will be automated using this command.
    cmds:
      - pre-commit install --install-hooks
      - task: setup:front-end

  ##########################################################################
  # Internal dependencies for setting up the dev environment
  ##########################################################################

  setup:front-end:
    internal: true
    desc: Setup the dev environment for the Front End
    dir: ./front-end
    cmd: pnpm install
    sources:
      - package.json
    generates:
      - pnpm-lock.yaml
